In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
%matplotlib inline

In [2]:
poker= pd.read_csv('/home/sharon/Downloads/poker-hand-training-true.csv')

In [3]:
poker.head()

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5  T
0   1  10   1  11   1  13   1  12   1   1  9
1   2  11   2  13   2  10   2  12   2   1  9
2   3  12   3  11   3  13   3  10   3   1  9
3   4  10   4  11   4   1   4  13   4  12  9
4   4   1   4  13   4  12   4  11   4  10  9

In [4]:
poker.shape

(25010, 11)

In [5]:
poker.isnull().sum()

S1    0
C1    0
S2    0
C2    0
S3    0
C3    0
S4    0
C4    0
S5    0
C5    0
T     0
dtype: int64

In [6]:
X_train = np.array(poker)[:, 0:-1]
X_train[:11]

array([[ 1, 10,  1, 11,  1, 13,  1, 12,  1,  1],
       [ 2, 11,  2, 13,  2, 10,  2, 12,  2,  1],
       [ 3, 12,  3, 11,  3, 13,  3, 10,  3,  1],
       [ 4, 10,  4, 11,  4,  1,  4, 13,  4, 12],
       [ 4,  1,  4, 13,  4, 12,  4, 11,  4, 10],
       [ 1,  2,  1,  4,  1,  5,  1,  3,  1,  6],
       [ 1,  9,  1, 12,  1, 10,  1, 11,  1, 13],
       [ 2,  1,  2,  2,  2,  3,  2,  4,  2,  5],
       [ 3,  5,  3,  6,  3,  9,  3,  7,  3,  8],
       [ 4,  1,  4,  4,  4,  2,  4,  3,  4,  5],
       [ 1,  1,  2,  1,  3,  9,  1,  5,  2,  3]])

In [7]:
y_train= np.array(poker["T"])
y_train[:11]

array([9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 1])


## Decision tree algorithm

In [8]:
dtc = tree.DecisionTreeClassifier()
dtc.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [9]:
poker_test= pd.read_csv('/home/sharon/Downloads/poker-hand-testing.csv')

In [10]:
poker_test.head()

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5  T
0   1   1   1  13   2   4   2   3   1  12  0
1   3  12   3   2   3  11   4   5   2   5  1
2   1   9   4   6   1   4   3   2   3   9  1
3   1   4   3  13   2  13   2   1   3   6  1
4   3  10   2   7   1   2   2  11   4   9  0

In [11]:
X_test = np.array(poker_test)[:, 0:-1]
X_test[:11]

array([[ 1,  1,  1, 13,  2,  4,  2,  3,  1, 12],
       [ 3, 12,  3,  2,  3, 11,  4,  5,  2,  5],
       [ 1,  9,  4,  6,  1,  4,  3,  2,  3,  9],
       [ 1,  4,  3, 13,  2, 13,  2,  1,  3,  6],
       [ 3, 10,  2,  7,  1,  2,  2, 11,  4,  9],
       [ 1,  3,  4,  5,  3,  4,  1, 12,  4,  6],
       [ 2,  6,  4, 11,  2,  3,  4,  9,  1,  7],
       [ 3,  2,  4,  9,  3,  7,  4,  3,  4,  5],
       [ 4,  4,  3, 13,  1,  8,  3,  9,  3, 10],
       [ 1,  9,  3,  8,  4,  4,  1,  7,  3,  5],
       [ 4,  7,  3, 12,  1, 13,  1,  9,  2,  6]])

In [12]:
y_test= np.array(poker_test["T"])
y_test[:11]

array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [13]:
dtc.predict(X_test)

array([0, 0, 1, ..., 1, 1, 0])

In [14]:
dtc.score(X_test, y_test)

0.478889

# Improving the test score using one hot encoding

In [21]:
# importing one hot encoder from sklearn 
from sklearn.preprocessing import OneHotEncoder 


In [22]:
onehotencoder = OneHotEncoder( categories='auto').fit(X_train)
  
New_X_train = onehotencoder.transform(X_train).toarray() 

In [23]:
New_X_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [24]:
New_X_test = onehotencoder.transform(X_test).toarray() 
New_X_test

array([[1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [31]:
new_dtc = tree.DecisionTreeClassifier()
new_dtc.fit(New_X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [32]:
new_dtc.predict(New_X_test)

array([1, 2, 1, ..., 1, 2, 1])

In [33]:
new_dtc.score(New_X_test, y_test) # Score improved by 0.1

0.573772

## Random forest algorithm

In [28]:
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)

/home/sharon/.local/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [29]:
rfc.predict(X_test)

array([0, 0, 0, ..., 0, 1, 0])

In [30]:
rfc.score(X_test, y_test)

0.563304

In [35]:
new_rfc=RandomForestClassifier()
new_rfc.fit(New_X_train,y_train)

/home/sharon/.local/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [36]:
new_rfc.predict(New_X_test)

array([1, 0, 0, ..., 1, 0, 1])

In [37]:
new_rfc.score(New_X_test, y_test)

0.579167